config/routes.rb
Rails.application.routes.draw do
  resources :gads_auths
  resources :oauth2_tokens
  resources :oauth2_configs
  get '/', to: 'homes#index'
  root :to => "home#index"
  get "login/prompt", to: 'logins#prompt'
  get "login/callback", to: 'logins#callback'
  get "login/logout", to: 'logins#logout'
  get "login/", to: 'logins#index'

  get "login/prompt_ga", to: 'logins#prompt_ga'
  get "login/callback_ga", to: 'logins#callback_ga'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/oauth2_token.rb
# == Schema Information
#
# Table name: oauth2_tokens
#
#  id            :bigint(8)        not null, primary key
#  access_token  :string
#  token_type    :string
#  refresh_token :string
#  expiry        :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#

class Oauth2Token < ApplicationRecord

  validates :access_token, presence: true

  def self.refresh_token_if_expired
    if self.token_expired?
      response    = RestClient.post "#{ENV['DOMAIN']}oauth2/token", :grant_type => 'refresh_token', :refresh_token => self.refresh_token, :client_id => ENV['APP_ID'], :client_secret => ENV['APP_SECRET']
      refreshhash = JSON.parse(response.body)

      token_will_change!
      expiresat_will_change!

      self.token     = refreshhash['access_token']
      self.expiry = DateTime.now + refreshhash["expires_in"].to_i.seconds

      self.save
      puts 'Saved'
    end
  end

  def self.token_expired?
    expiry = Time.at(self.expiry)
    return true if expiry < Time.now # expired token, so we should quickly return
    token_expires_at = expiry
    save if changed?
    false # token not expired. :D
  end
end

app/controllers/application_controller.rb
require 'adwords_api'
require 'google/apis/analytics_v3'
require 'google/api_client/client_secrets'
require 'google/api_client/auth/key_utils'
class ApplicationController < ActionController::Base

  before_action :authenticate
  protect_from_forgery

  private

  # Returns the API version in use.
  def get_api_version()
    return :v201806
  end

  # Returns currently selected account.
  def selected_account()
    @selected_account ||= session[:selected_account]
    return @selected_account
  end

  # Sets current account to the specified one.
  def selected_account=(new_selected_account)
    @selected_account = new_selected_account
    session[:selected_account] = @selected_account
  end

  # Checks if we have a valid credentials.
  def authenticate()
    token_ads = session[:token_adwords]
    token_ga = session[:token_analytics]
    return redirect_to login_path if token_ads.nil? && token_ga.nil?
    return !token_ads.nil? || !token_ga.nil?
  end

  # Returns an API object.
  def get_adwords_api()
    @api ||= create_adwords_api()
    return @api
  end

  # Creates an instance of AdWords API class. Uses a configuration file and
  # Rails config directory.
  def create_adwords_api()
    config_filename = File.join(Rails.root, 'config', 'adwords_api.yml')
    @api = AdwordsApi::Api.new(config_filename)
    token = session[:token_adwords]
    # If we have an OAuth2 token in session we use the credentials from it.
    if token
      credentials = @api.credential_handler()
      credentials.set_credential(:oauth2_token, token)
      credentials.set_credential(:client_customer_id, selected_account)
    end
    return @api
  end

  def create_analytis__request
    ga = Signet::OAuth2::Client.new(
      :authorization_uri => 'https://accounts.google.com/o/oauth2/auth',
      :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      :scope => 'https://www.googleapis.com/auth/analytics.readonly',
      :client_id => '471993607899-b9jroakasqlafkp0at5l76fdps6cvjr9.apps.googleusercontent.com',
      :client_secret => 'goHZRbOWTAKKfhS_y9MnxrqS',
      :redirect_uri => 'http://localhost:3000/login/callback_ga'
    )
    return ga
  end
end

app/controllers/homes_controller.rb
require 'rest-client'
class HomesController < ApplicationController
  def index
    @token_adwords = Oauth2Token.where(access_token: session[:token_adwords]["access_token"]).first if session[:token_adwords]
    @token_analytics = Oauth2Token.where(access_token: session[:token_analytics]["access_token"]).first if session[:token_analytics].present?


    @allToken = Oauth2Token.all.order(created_at: :DESC)
  end
end

app/controllers/logins_controller.rb
require 'adwords_api'
require 'google/apis/analytics_v3'
class LoginsController < ApplicationController

  skip_before_action :authenticate

  GOOGLE_LOGOUT_URL = 'https://www.google.com/accounts/Logout'

  def index
  end

  def prompt_ga
    if session[:token_analytics].blank?
      ga_alias = Google::Apis::AnalyticsV3
      @ga = ga_alias::AnalyticsService.new
      @ga.authorization = Signet::OAuth2::Client.new(
        :authorization_uri => 'https://accounts.google.com/o/oauth2/auth',
        :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
        :scope => 'https://www.googleapis.com/auth/analytics.readonly',
        :client_id => ENV['OAUTH2_CLIENT_ID'],
        :client_secret => ENV['OAUTH2_CLIENT_SECRET'],
        :redirect_uri => login_callback_ga_url
      )
      p 'xxx'
      p @ga
      redirect_to(@ga.authorization.authorization_uri.to_s)
    else
      redirect_to root_path
    end
  end


  def prompt()
    api = get_adwords_api()
    if session[:token_adwords]
      oauth2_ga = Oauth2Token.new(access_token: session[:token_adwords][:access_token], token_type: "adwords", refresh_token: session[:token_adwords][:refresh_token], expiry: session[:token_adwords][:expires_in], issued_at: session[:token_adwords][:issued_at])
      return redirect_to root_path if oauth2_ga.save
      redirect_to login_path
    else
      begin
        token = api.authorize({:oauth2_callback => login_callback_url})
      rescue AdsCommon::Errors::OAuth2VerificationRequired => e
        @login_url = e.oauth_url
      end
    end
  end

  def callback_ga
    ga_alias = Google::Apis::AnalyticsV3
    @ga = ga_alias::AnalyticsService.new
    @ga.authorization = Signet::OAuth2::Client.new(
      :authorization_uri => 'https://accounts.google.com/o/oauth2/auth',
      :token_credential_uri => 'https://accounts.google.com/o/oauth2/token',
      :scope => 'https://www.googleapis.com/auth/analytics.readonly',
      :client_id => ENV['OAUTH2_CLIENT_ID'],
      :client_secret => ENV['OAUTH2_CLIENT_SECRET'],
      :redirect_uri => login_callback_ga_url
    )

    begin
      @ga.authorization.code = params['code']
      p 'session ga'
      p session[:token_analytics] = @ga.authorization.fetch_access_token!
      if session[:token_analytics]
        flash.notice = 'Authorized successfully'
        oauth2_ga = Oauth2Token.new(access_token: session[:token_analytics]['access_token'], token_type: "analytics", refresh_token: session[:token_analytics]['refresh_token'], expiry: session[:token_analytics]['expires_in'], issued_at: session[:token_analytics]['issued_at'])
        return redirect_to root_path if oauth2_ga.save
        return  redirect_to login_path
      end
    rescue Signet::AuthorizationError => e
      p e
      flash.alert = "Authorization failed #{e}"
      redirect_to login_path
    end
  end

  def callback()
    api = get_adwords_api()
    begin
      session[:token_adwords] = api.authorize(
          {
            :oauth2_callback => login_callback_url,
            :oauth2_verification_code => params[:code]
          }
      )
      flash.notice = 'Authorized successfully'
      oauth2_ga = Oauth2Token.new(access_token: session[:token_adwords][:access_token], token_type: "adwords", refresh_token: session[:token_adwords][:refresh_token], expiry: session[:token_adwords][:expires_in], issued_at: session[:token_adwords][:issued_at])
      return redirect_to root_path if oauth2_ga.save
      redirect_to login_path
    rescue AdsCommon::Errors::OAuth2VerificationRequired => e
      flash.alert = 'Authorization failed'
      redirect_to login_prompt_path
    end
  end

  def logout()
    [:selected_account, :token_adwords, :token_analytics].each {|key| session.delete(key)}
    redirect_to GOOGLE_LOGOUT_URL
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gads_auths_helper.rb
module GadsAuthsHelper
end

app/helpers/oauth2_configs_helper.rb
module Oauth2ConfigsHelper
end

app/helpers/oauth2_tokens_helper.rb
module Oauth2TokensHelper
end

app/views/homes/index.html.slim
p
  | Hello
- if flash[:alert]
  .alert
    = flash[:alert]
- if flash[:notice]
  .notice
    = flash[:notice]
= link_to 'logout', login_logout_path if session[:token_adwords].present?
p
  = link_to 'Get token_adwords', login_prompt_path if session[:token_adwords].blank?
p
  = link_to 'Get token_analytics', login_prompt_ga_path if session[:token_analytics].blank?
h1
  | Your token_adwords token:
= @token_adwords.inspect if @token_adwords.present?

p access_token
textarea rows='2'
  = @token_adwords.try(:access_token)
p refresh_token
textarea rows='2'
  = @token_adwords.try(:refresh_token)
hr
h1
  | Your token_analytics token:
= @token_analytics.inspect if @token_analytics.present?
p access_token
textarea rows='2'
  = @token_analytics.try(:access_token)
p refresh_token
textarea rows='2'
  = @token_analytics.try(:refresh_token)


hr
p
|All token
ul
  - @allToken.each do |k|
    li
      |ID:
      = k.id
      br
      b
        | access_token #{k.token_type}
      textarea rows='2'
        = k.access_token
      | refresh_token
      textarea rows='2'
        = k.refresh_token

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | DemoAdwordsApi
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  body
    = yield

script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-117767126-2"
javascript:
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-117767126-2');

app/views/logins/index.html.slim
h1
  | Authorization required
- if flash[:alert]
  .alert
    = flash[:alert]
- if flash[:notice]
  .notice
    = flash[:notice]
p
  | Please authorize with a google account first:
p
  | <a href="
  = login_prompt_path
  | ">Proceed Adwords
p
  | <a href="
  = login_prompt_ga_path
  | ">Proceed GA

app/views/logins/logout.html.slim
|  Logging out of Google Services: 
iframe[src="https://www.google.com/accounts/Logout"]

app/views/logins/prompt.html.slim
h1
  | Authorization required
- if flash[:alert]
  .alert
    = flash[:alert]
- if flash[:notice]
  .notice
    = flash[:notice]
p
  | Please authorize with a google account first:
p
  | <a href="
  = @login_url
  | ">Proceed Adwords

app/views/logins/prompt_ga.html.slim
h1
  | Authorization required
- if flash[:alert]
  .alert
    = flash[:alert]
- if flash[:notice]
  .notice
    = flash[:notice]
p
  | Please authorize with a google account first:
p
  | <a href="
  = login_prompt_ga_path
  | ">Proceed GA